services:
    api:
        image: dotnet-3.1-img
        build: .
        ports:
            - "5000:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        container_name: importation-api
